config/routes.rb
Rails.application.routes.draw do

  # Routing concerns
  concern :imageable do
    resources :images, shallow: true, only: [:create, :destroy]
  end

  # Routes
  namespace :admin do
    resources :countries, concerns: :imageable, except: [:destroy] do
      resources :cities, only: [:index, :new, :create]
    end

    resources :cities, concerns: :imageable, only: [:show, :edit, :update] do
      resources :locations, only: [:index, :new, :create]
    end

    resources :locations, concerns: :imageable, only: [:show, :edit, :update, :destroy]

    resources :location_categories do
      resources :locations, only: [:index]
    end

    resources :users, only: [:index]

    root to: 'countries#index'
  end


  resources :countries, only: [:index, :new, :create] do
    resources :cities, only: [:index, :new, :create]
  end

  resources :cities, only: [:index] do
    resources :locations, only: [:index, :new, :create]
  end

  resources :locations, only: [:show]

  # Omniauth
  get    '/auth/:provider/callback', to: 'sessions#create'
  get    '/auth/failure',            to: 'static_pages#landingpage'
  get    'signin',                   to: 'sessions#new'
  post   'signin',                   to: 'sessions#create'
  delete 'signout',                  to: 'sessions#destroy'

  # Static pages
  get 'landingpage'      => 'static_pages#landingpage'
  get 'about'            => 'static_pages#about'
  get 'privacy'          => 'static_pages#privacy'
  get 'terms_of_service' => 'static_pages#terms_of_service'
  get 'contribute'       => 'static_pages#contribute'

  # SEO sitemap
  get 'sitemap' => 'sitemaps#index', defaults: { format: 'xml' }

  root to: "static_pages#landingpage"

  #################################################################
  # WARNING                                                       #
  # Do not put anything below the slug urls, because it will be   #
  # resolved as slug route.                                       #
  #################################################################

  # Slug based country URLs
  get ':country_slug' => 'countries#show',
        constraints: {
          country_slug:      /[a-z_]+/
        }, as: 'country_slug'


  # Slug based city URLs
  get ':country_slug/:city_slug' => 'cities#show',
        constraints: {
          country_slug:      /[a-z_]+/,
          city_slug:         /[a-z_]+/
        }, as: 'city_slug'


  # Slug based location URLs
  get ':country_slug/:city_slug/:location_slug' => 'locations#show',
        constraints: {
          country_slug:  /[a-z_]+/,
          city_slug:     /[a-z_]+/,
          location_slug: /[a-z_]+/
        }, as: 'location_slug'

end

app/models/location.rb
class Location < ActiveRecord::Base

  # Modules
  include Imagable

  # Associations
  belongs_to :city
  belongs_to :location_category
  belongs_to :user

  # Validations
  validates :name, presence: true
  validates :slug, presence: true,
                   uniqueness: { scope: :city },
                   format: { with: /\A[a-z_]+\z/ }
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :location_category, presence: true

  # Scopes
  default_scope { order(name: :asc) }

  def country
    city.country
  end

  def self.find_by_slug(country_slug, city_slug, slug)
    includes(:city => :country)
     .where(             slug: slug          )
     .where(cities:    { slug: city_slug    })
     .where(countries: { slug: country_slug }).first!
  end

end

app/controllers/admin/locations_controller.rb
module Admin
  class LocationsController < BaseController

    before_action :set_city,              only: [:index, :new, :create]
    before_action :set_location_category, only: [:index]

    before_action :load_map_javascript, except: [:index, :destroy]

    def index
      if @city.present?
        @locations = Location.where(city: @city)
      elsif @location_category.present?
        @locations = Location.where(location_category: @location_category)
      end
    end

    def show
      @location = Location.find(params[:id])
    end

    def new
      @location = Location.new
    end

    def create
      @location = Location.new(location_params)

      @city.locations << @location

      if @location.save
        redirect_to admin_city_locations_path(@city)
      else
        render :new
      end
    end

    def edit
      @location = Location.find(params[:id])
    end

    def update
      @location = Location.find(params[:id])

      if @location.update(location_params)
        redirect_to admin_city_locations_path(@location.city)
      else
        render :edit
      end
    end

    def destroy
      @location = Location.find(params[:id])
      @location.destroy

      redirect_to admin_city_locations_path(@location.city)
    end

    private

    def location_params
      if params[:location].present?
        params[:location].permit(:name,
                                 :slug,
                                 :description,
                                 :history,
                                 :website,
                                 :latitude,
                                 :longitude,
                                 :default_zoom_level,
                                 :location_category_id,
                                 :user_id
                                )
      else
        {}
      end
    end

    def set_city
      if params[:city_id].present?
        @city = City.find(params[:city_id])
      end
    end

    def set_location_category
      if params[:location_category_id].present?
        @location_category = LocationCategory.find(params[:location_category_id])
      end
    end

  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  before_action :requires_login, only: [:new, :create]
  before_action :load_map_javascript

  def index
    @city = City.find(params[:city_id])
    @locations = @city.locations

    respond_to do |format|
      format.json { render layout: false }
    end
  end

  def new
    @city = City.find(params[:city_id])
    @location = Location.new
  end

  def create
    @city = City.find(params[:city_id])
    @location = Location.new(location_params.merge(
                  slug: slug_from_name(location_params[:name]),
                  user_id: current_user.id,
                  city_id: @city.id
                ))

    if @location.save
      redirect_to back_or_default(city_slug_path(country_slug: @city.country.slug, city_slug: @city.slug))
    else
      render :new
    end
  end

  def show
    if params[:id].present?
      @location = Location.find(params[:id])
    else
      @location = Location.find_by_slug(params[:country_slug], params[:city_slug], params[:location_slug])
    end

    # Tracking
    mixpanel_track_location_page_view(@location)

    respond_to do |format|
      format.html
      format.json { render layout: false }
    end
  end

  private

  def location_params
    if params[:location].present?
      params[:location].permit(
                               :name,
                               :description,
                               :website,
                               :latitude,
                               :longitude,
                               :default_zoom_level,
                               :location_category_id
                              )
    else
      {}
    end
  end

  # REFACTORING: Move to a module
  def slug_from_name(name)
    name.gsub(' ', '_').downcase
  end
end

app/views/admin/locations/_form.slim
= form_for [:admin, country, city, location] do |location_form|

  - unless location.persisted?
    = location_form.hidden_field :user_id, { value: current_user.id }

  .form-group
    = location_form.label :name
    = location_form.text_field :name, disabled: !editable, class: 'form-control'

  .form-group
    = location_form.label :slug
    = location_form.text_field :slug, disabled: !editable, class: 'form-control'

  .form-group
    = location_form.label :location_category
    = location_form.collection_select :location_category_id, LocationCategory.all, :id, :name, { prompt: 'Select a category' }, { disabled: !editable, class: 'form-control' }

  .form-group
    = location_form.label :description
    = location_form.text_area :description, disabled: !editable, class: 'form-control textarea_wysihtml'

  .form-group
    = location_form.label :history
    = location_form.text_area :history, disabled: !editable, class: 'form-control textarea_wysihtml'

  .form-group
    = location_form.label :website
    = location_form.text_field :website, placeholder: 'http://example.com', disabled: !editable, class: 'form-control'

  .form-group
    .map.map_fixed-height
      .map__backsight
      .map__canvas {
                      data-lat="#{city.latitude}"
                      data-lng="#{city.longitude}"
                      data-zoom="#{city.default_zoom_level}"
                      data-draggable="#{editable}"
                      data-zoomable="#{editable}"
                    }

      = location_form.text_field :latitude, class: 'map__input map__input_lat'
      = location_form.text_field :longitude, class: 'map__input map__input_lng'
      = location_form.text_field :default_zoom_level, class: 'map__input map__input_zoom-level'

  - if editable
    .form-group
      = location_form.submit 'Save', class: 'btn btn-primary'

- if location.persisted?
  h3 Images
  - if location.images.any?
    - location.images.each do |image|
      = image_tag image.file.url(:small)
      = button_to 'Delete', admin_image_path(image, referrer_param => current_path), method: :delete, class: 'btn btn-danger'
  - else
    .alert.alert-info There are no images for this location.

  - if editable
    = form_for [:admin, location, Image.new] do |image_form|
      = hidden_referrer_input_tag
      .form-group
        = image_form.file_field :file, disabled: !editable, class: 'form-control'

      .form-group
        = image_form.submit 'Upload', class: 'btn btn-primary'

app/views/admin/locations/edit.html.slim
br

ol.breadcrumb
  li = link_to 'Admin', admin_root_path
  li = link_to @location.country.name, admin_country_path(@location.country)
  li = link_to @location.city.name, admin_city_path(@location.city)
  li.active = @location.name

ul.nav.nav-tabs
  li = link_to 'Show', admin_location_path(@location)
  li.active = link_to 'Edit', edit_admin_location_path(@location)

br

= render 'form', { country: @country, city: @city, location: @location, editable: true }

br
br

app/views/admin/locations/index.html.slim
- if @city.present?
  br

  ol.breadcrumb
    li = link_to 'Admin', admin_root_path
    li = link_to @city.country.name, admin_country_path(@city.country)
    li.active = @city.name

  ul.nav.nav-tabs
    li = link_to 'Show', admin_city_path(@city)
    li = link_to 'Edit', edit_admin_city_path(@city)
    li.active = link_to 'Locations', admin_city_locations_path(@city)

br

- if @locations.any?
  div.table-responsive
    table.table.table-striped.table-hover
      thead
        tr
          th Location
          th City
          th Caegory
          th Slug
          th Actions

      tbody
        - @locations.each do |location|
          tr
            td = link_to location.name, admin_location_path(location)
            td = link_to location.city.name, admin_city_path(location.city)
            td = link_to location.location_category.name, admin_location_category_locations_path(location.location_category)
            td = location.slug
            td = button_to 'Delete', admin_location_path(location),
                                     method: :delete,
                                     data: { confirm: "Are you sure?" },
                                     class: 'btn btn-danger btn-xs'

- else
  .alert.alert-info There are no locations.

- if @city.present?
  = link_to 'New location', new_admin_city_location_path(@city), class: 'btn btn-primary'

br
br

app/views/admin/locations/new.html.slim
h1 New location

= link_to 'Locations list', admin_city_locations_path(@city)

br
br

= render 'form', { country: @country, city: @city, location: @location, editable: true }

app/views/admin/locations/show.html.slim
br

ol.breadcrumb
  li = link_to 'Admin', admin_root_path
  li = link_to @location.country.name, admin_country_path(@location.country)
  li = link_to @location.city.name, admin_city_path(@location.city)
  li.active = @location.name

ul.nav.nav-tabs
  li.active = link_to 'Show', admin_location_path(@location)
  li = link_to 'Edit', edit_admin_location_path(@location)

br

= render 'form', { country: @country, city: @city, location: @location, editable: false }

br
br