config/routes.rb
Rails.application.routes.draw do

  # Routing concerns
  concern :imageable do
    resources :images, shallow: true, only: [:create, :destroy]
  end

  # Routes
  namespace :admin do
    resources :countries, concerns: :imageable, except: [:destroy] do
      resources :cities, only: [:index, :new, :create]
    end

    resources :cities, concerns: :imageable, only: [:show, :edit, :update] do
      resources :locations, only: [:index, :new, :create]
    end

    resources :locations, concerns: :imageable, only: [:show, :edit, :update, :destroy]

    resources :location_categories do
      resources :locations, only: [:index]
    end

    resources :users, only: [:index]

    root to: 'countries#index'
  end


  resources :countries, only: [:index, :new, :create] do
    resources :cities, only: [:index, :new, :create]
  end

  resources :cities, only: [:index] do
    resources :locations, only: [:index, :new, :create]
  end

  resources :locations, only: [:show]

  # Omniauth
  get    '/auth/:provider/callback', to: 'sessions#create'
  get    '/auth/failure',            to: 'static_pages#landingpage'
  get    'signin',                   to: 'sessions#new'
  post   'signin',                   to: 'sessions#create'
  delete 'signout',                  to: 'sessions#destroy'

  # Static pages
  get 'landingpage'      => 'static_pages#landingpage'
  get 'about'            => 'static_pages#about'
  get 'privacy'          => 'static_pages#privacy'
  get 'terms_of_service' => 'static_pages#terms_of_service'
  get 'contribute'       => 'static_pages#contribute'

  # SEO sitemap
  get 'sitemap' => 'sitemaps#index', defaults: { format: 'xml' }

  root to: "static_pages#landingpage"

  #################################################################
  # WARNING                                                       #
  # Do not put anything below the slug urls, because it will be   #
  # resolved as slug route.                                       #
  #################################################################

  # Slug based country URLs
  get ':country_slug' => 'countries#show',
        constraints: {
          country_slug:      /[a-z_]+/
        }, as: 'country_slug'


  # Slug based city URLs
  get ':country_slug/:city_slug' => 'cities#show',
        constraints: {
          country_slug:      /[a-z_]+/,
          city_slug:         /[a-z_]+/
        }, as: 'city_slug'


  # Slug based location URLs
  get ':country_slug/:city_slug/:location_slug' => 'locations#show',
        constraints: {
          country_slug:  /[a-z_]+/,
          city_slug:     /[a-z_]+/,
          location_slug: /[a-z_]+/
        }, as: 'location_slug'

end

app/models/location_category.rb
class LocationCategory < ActiveRecord::Base
  has_many :locations

  default_scope { order(name: :asc) }
end

app/controllers/admin/location_categories_controller.rb
module Admin
  class LocationCategoriesController < BaseController

    before_action :set_location_category, only: [:show, :edit, :update, :destroy]

    def index
      @location_categories = LocationCategory.all
    end

    def show
    end

    def new
      @location_category = LocationCategory.new
    end

    def create
      @location_category = LocationCategory.new(location_category_params)

      if @location_category.save
        redirect_to admin_location_categories_path
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @location_category.update(location_category_params)
        redirect_to admin_location_categories_path
      else
        render :edit
      end
    end

    def destroy
      @location_category.destroy

      redirect_to admin_location_categories_path
    end

    private

    def set_location_category
      @location_category = LocationCategory.find(params[:id])
    end

    def location_category_params
      if params[:location_category].present?
        params[:location_category].permit(:name)
      else
        {}
      end
    end

  end
end

app/views/admin/location_categories/_form.slim
= form_for [:admin, location_category] do |location_category_form|

  .form-group
    = location_category_form.label :name
    = location_category_form.text_field :name, disabled: !editable, class: 'form-control'

  - if editable
    .form-group
      = location_category_form.submit 'Save', class: 'btn btn-primary'

app/views/admin/location_categories/edit.html.slim
h1 Edit category

ol.breadcrumb
  li = link_to 'Admin', admin_root_path
  li = link_to 'Location categories', admin_location_categories_path
  li.active = @location_category.name

ul.nav.nav-tabs
  li = link_to 'Show', admin_location_category_path(@location_category)
  li.active = link_to 'Edit', edit_admin_location_category_path(@location_category)

= render 'form', { location_category: @location_category, editable: true }

app/views/admin/location_categories/index.html.slim
h1 Location categories

br

ol.breadcrumb
  li = link_to 'Admin', admin_root_path
  li.active Location categories

- if @location_categories.any?
  div.table-responsive
    table.table.table-striped.table-hover
      thead
        tr
          th Name
          th Locations

      tbody
        - @location_categories.each do |location_category|
          tr
            td = link_to location_category.name, admin_location_category_path(location_category)
            td = link_to location_category.locations.count, admin_location_category_locations_path(location_category)

- else
  .alert.alert-info There are no location categories.

= link_to 'New location category', new_admin_location_category_path, class: 'btn btn-primary'

br
br

app/views/admin/location_categories/new.html.slim
h1 New category

= render 'form', { location_category: @location_category, editable: true }

app/views/admin/location_categories/show.html.slim
h1 Location category

ol.breadcrumb
  li = link_to 'Admin', admin_root_path
  li = link_to 'Location categories', admin_location_categories_path
  li.active = @location_category.name

ul.nav.nav-tabs
  li.active = link_to 'Show', admin_location_category_path(@location_category)
  li = link_to 'Edit', edit_admin_location_category_path(@location_category)

br

= render 'form', { location_category: @location_category, editable: false }