config/routes.rb
Rails.application.routes.draw do

  # Routing concerns
  concern :imageable do
    resources :images, shallow: true, only: [:create, :destroy]
  end

  # Routes
  namespace :admin do
    resources :countries, concerns: :imageable, except: [:destroy] do
      resources :cities, only: [:index, :new, :create]
    end

    resources :cities, concerns: :imageable, only: [:show, :edit, :update] do
      resources :locations, only: [:index, :new, :create]
    end

    resources :locations, concerns: :imageable, only: [:show, :edit, :update, :destroy]

    resources :location_categories do
      resources :locations, only: [:index]
    end

    resources :users, only: [:index]

    root to: 'countries#index'
  end


  resources :countries, only: [:index, :new, :create] do
    resources :cities, only: [:index, :new, :create]
  end

  resources :cities, only: [:index] do
    resources :locations, only: [:index, :new, :create]
  end

  resources :locations, only: [:show]

  # Omniauth
  get    '/auth/:provider/callback', to: 'sessions#create'
  get    '/auth/failure',            to: 'static_pages#landingpage'
  get    'signin',                   to: 'sessions#new'
  post   'signin',                   to: 'sessions#create'
  delete 'signout',                  to: 'sessions#destroy'

  # Static pages
  get 'landingpage'      => 'static_pages#landingpage'
  get 'about'            => 'static_pages#about'
  get 'privacy'          => 'static_pages#privacy'
  get 'terms_of_service' => 'static_pages#terms_of_service'
  get 'contribute'       => 'static_pages#contribute'

  # SEO sitemap
  get 'sitemap' => 'sitemaps#index', defaults: { format: 'xml' }

  root to: "static_pages#landingpage"

  #################################################################
  # WARNING                                                       #
  # Do not put anything below the slug urls, because it will be   #
  # resolved as slug route.                                       #
  #################################################################

  # Slug based country URLs
  get ':country_slug' => 'countries#show',
        constraints: {
          country_slug:      /[a-z_]+/
        }, as: 'country_slug'


  # Slug based city URLs
  get ':country_slug/:city_slug' => 'cities#show',
        constraints: {
          country_slug:      /[a-z_]+/,
          city_slug:         /[a-z_]+/
        }, as: 'city_slug'


  # Slug based location URLs
  get ':country_slug/:city_slug/:location_slug' => 'locations#show',
        constraints: {
          country_slug:  /[a-z_]+/,
          city_slug:     /[a-z_]+/,
          location_slug: /[a-z_]+/
        }, as: 'location_slug'

end

app/models/country.rb
class Country < ActiveRecord::Base

  # Modules
  include Imagable

  # Associations
  belongs_to :user
  has_many :cities, dependent: :destroy

  # Validations
  validates :name, presence: true
  validates :slug, presence: true,
                   uniqueness: true,
                   format: { with: /\A[a-z_]+\z/ }
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :default_zoom_level, presence: true

  def self.find_by_slug(slug)
    Country.where(slug: slug).first!
  end
end

app/controllers/admin/countries_controller.rb
module Admin
  class CountriesController < BaseController

    before_action :load_map_javascript, except: [:index]

    def index
      @countries = Country.all
    end

    def show
      @country = Country.find(params[:id])
    end

    def new
      @country = Country.new
    end

    def create
      @country = Country.new(country_params)

      if @country.save
        redirect_to admin_countries_path
      else
        render :new
      end
    end

    def edit
      @country = Country.find(params[:id])
    end

    def update
      @country = Country.find(params[:id])

      if @country.update(country_params)
        redirect_to admin_countries_path
      else
        render :edit
      end
    end

    private

    def country_params
      if params[:country].present?
        params[:country].permit(:name,
                                :slug,
                                :latitude,
                                :longitude,
                                :default_zoom_level,
                                :general_information,
                                :user_id
                               )
      else
        {}
      end
    end

  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  before_action :requires_login, only: [:new, :create]
  before_action :load_map_javascript

  def index
    @countries = Country.all.order(name: :asc)

    respond_to do |format|
      format.html
      format.json { render layout: false }
    end
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new(country_params.merge(
                slug: slug_from_name(country_params[:name]),
                user_id: current_user.id
              ))

    if @country.save
      redirect_to back_or_default(countries_path)
    else
      render :new
    end
  end

  def show
    @country = Country.where(slug: params[:country_slug]).first

    if @country.nil?
      raise ActiveRecord::RecordNotFound
    end

    @cities = @country.cities.published.order(capital: :desc).order(population: :desc)

    # Tracking
    mixpanel_track_country_page_view(@country)
  end

  private

  def country_params
    if params[:country].present?
      params[:country].permit(:name, :latitude, :longitude, :default_zoom_level)
    else
      {}
    end
  end

  # REFACTORING: Move to a module
  def slug_from_name(name)
    name.gsub(' ', '_').downcase
  end
end

app/views/admin/countries/_form.slim
= form_for [:admin, country] do |country_form|

  - unless country.persisted?
    = country_form.hidden_field :user_id, { value: current_user.id }

  .form-group
    = country_form.label :name
    = country_form.text_field :name, disabled: !editable, class: 'form-control'

  .form-group
    = country_form.label :slug
    = country_form.text_field :slug, disabled: !editable, class: 'form-control'

  .form-group
    = country_form.label :general_information
    = country_form.text_area :general_information, disabled: !editable, class: 'form-control textarea_wysihtml'

  .form-group
    .map.map_fixed-height
      .map__backsight
      .map__canvas {
                      data-lat="#{country.latitude}"
                      data-lng="#{country.longitude}"
                      data-zoom="#{country.default_zoom_level}"
                      data-draggable="#{editable}"
                      data-zoomable="#{editable}"
                    }

      = country_form.text_field :latitude, class: 'map__input map__input_lat'
      = country_form.text_field :longitude, class: 'map__input map__input_lng'
      = country_form.text_field :default_zoom_level, class: 'map__input map__input_zoom-level'


  - if editable
    .form-group
      = country_form.submit 'Save', class: 'btn btn-primary'

- if country.persisted?
  h3 Images
  - if country.images.any?
    - country.images.each do |image|
      = image_tag image.file.url(:small)
      = button_to 'Delete', admin_image_path(image, referrer_param => current_path), method: :delete, class: 'btn btn-danger'
  - else
    .alert.alert-info There are no images for this country.

  - if editable
    = form_for [:admin, country, Image.new] do |image_form|
      = hidden_referrer_input_tag
      .form-group
        = image_form.file_field :file, disabled: !editable, class: 'form-control'


      .form-group
        = image_form.submit 'Upload', class: 'btn btn-primary'

app/views/admin/countries/edit.html.slim
br

ol.breadcrumb
  li = link_to 'Admin', admin_root_path
  li.active = @country.name

ul.nav.nav-tabs
  li = link_to 'Show', admin_country_path(@country)
  li.active = link_to 'Edit', edit_admin_country_path(@country)
  li = link_to 'Cities', admin_country_cities_path(@country)

br

= render 'form', { country: @country, editable: true }

br
br

app/views/admin/countries/index.html.slim
br

ol.breadcrumb
  li = link_to 'Admin', admin_root_path
  li.active Countries

- if @countries.any?
  div.table-responsive
    table.table.table-striped.table-hover
      thead
        tr
          th Country
          th Slug
          th Cities
      tbody
        - @countries.each do |country|
          tr
            td #{link_to country.name, admin_country_path(country)}
            td = country.slug
            td #{link_to country.cities.size, admin_country_cities_path(country)}

- else
  .alert.alert-info There are no countries.

= link_to 'New country', new_admin_country_path, class: 'btn btn-primary'

br
br

app/views/admin/countries/new.html.slim
h1 New country

= link_to 'Countries list', admin_countries_path

br
br

= render 'form', { country: @country, editable: true }

app/views/admin/countries/show.html.slim
br

ol.breadcrumb
  li = link_to 'Admin', admin_root_path
  li.active = @country.name

ul.nav.nav-tabs
  li.active = link_to 'Show', admin_country_path(@country)
  li = link_to 'Edit', edit_admin_country_path(@country)
  li = link_to 'Cities', admin_country_cities_path(@country)

br

= render 'form', { country: @country, editable: false }

br
br