config/routes.rb
Rails.application.routes.draw do

  # Routing concerns
  concern :imageable do
    resources :images, shallow: true, only: [:create, :destroy]
  end

  # Routes
  namespace :admin do
    resources :countries, concerns: :imageable, except: [:destroy] do
      resources :cities, only: [:index, :new, :create]
    end

    resources :cities, concerns: :imageable, only: [:show, :edit, :update] do
      resources :locations, only: [:index, :new, :create]
    end

    resources :locations, concerns: :imageable, only: [:show, :edit, :update, :destroy]

    resources :location_categories do
      resources :locations, only: [:index]
    end

    resources :users, only: [:index]

    root to: 'countries#index'
  end


  resources :countries, only: [:index, :new, :create] do
    resources :cities, only: [:index, :new, :create]
  end

  resources :cities, only: [:index] do
    resources :locations, only: [:index, :new, :create]
  end

  resources :locations, only: [:show]

  # Omniauth
  get    '/auth/:provider/callback', to: 'sessions#create'
  get    '/auth/failure',            to: 'static_pages#landingpage'
  get    'signin',                   to: 'sessions#new'
  post   'signin',                   to: 'sessions#create'
  delete 'signout',                  to: 'sessions#destroy'

  # Static pages
  get 'landingpage'      => 'static_pages#landingpage'
  get 'about'            => 'static_pages#about'
  get 'privacy'          => 'static_pages#privacy'
  get 'terms_of_service' => 'static_pages#terms_of_service'
  get 'contribute'       => 'static_pages#contribute'

  # SEO sitemap
  get 'sitemap' => 'sitemaps#index', defaults: { format: 'xml' }

  root to: "static_pages#landingpage"

  #################################################################
  # WARNING                                                       #
  # Do not put anything below the slug urls, because it will be   #
  # resolved as slug route.                                       #
  #################################################################

  # Slug based country URLs
  get ':country_slug' => 'countries#show',
        constraints: {
          country_slug:      /[a-z_]+/
        }, as: 'country_slug'


  # Slug based city URLs
  get ':country_slug/:city_slug' => 'cities#show',
        constraints: {
          country_slug:      /[a-z_]+/,
          city_slug:         /[a-z_]+/
        }, as: 'city_slug'


  # Slug based location URLs
  get ':country_slug/:city_slug/:location_slug' => 'locations#show',
        constraints: {
          country_slug:  /[a-z_]+/,
          city_slug:     /[a-z_]+/,
          location_slug: /[a-z_]+/
        }, as: 'location_slug'

end

app/models/country.rb
class Country < ActiveRecord::Base

  # Modules
  include Imagable

  # Associations
  belongs_to :user
  has_many :cities, dependent: :destroy

  # Validations
  validates :name, presence: true
  validates :slug, presence: true,
                   uniqueness: true,
                   format: { with: /\A[a-z_]+\z/ }
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :default_zoom_level, presence: true

  def self.find_by_slug(slug)
    Country.where(slug: slug).first!
  end
end

app/controllers/admin/countries_controller.rb
module Admin
  class CountriesController < BaseController

    before_action :load_map_javascript, except: [:index]

    def index
      @countries = Country.all
    end

    def show
      @country = Country.find(params[:id])
    end

    def new
      @country = Country.new
    end

    def create
      @country = Country.new(country_params)

      if @country.save
        redirect_to admin_countries_path
      else
        render :new
      end
    end

    def edit
      @country = Country.find(params[:id])
    end

    def update
      @country = Country.find(params[:id])

      if @country.update(country_params)
        redirect_to admin_countries_path
      else
        render :edit
      end
    end

    private

    def country_params
      if params[:country].present?
        params[:country].permit(:name,
                                :slug,
                                :latitude,
                                :longitude,
                                :default_zoom_level,
                                :general_information,
                                :user_id
                               )
      else
        {}
      end
    end

  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  before_action :requires_login, only: [:new, :create]
  before_action :load_map_javascript

  def index
    @countries = Country.all.order(name: :asc)

    respond_to do |format|
      format.html
      format.json { render layout: false }
    end
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new(country_params.merge(
                slug: slug_from_name(country_params[:name]),
                user_id: current_user.id
              ))

    if @country.save
      redirect_to back_or_default(countries_path)
    else
      render :new
    end
  end

  def show
    @country = Country.where(slug: params[:country_slug]).first

    if @country.nil?
      raise ActiveRecord::RecordNotFound
    end

    @cities = @country.cities.published.order(capital: :desc).order(population: :desc)

    # Tracking
    mixpanel_track_country_page_view(@country)
  end

  private

  def country_params
    if params[:country].present?
      params[:country].permit(:name, :latitude, :longitude, :default_zoom_level)
    else
      {}
    end
  end

  # REFACTORING: Move to a module
  def slug_from_name(name)
    name.gsub(' ', '_').downcase
  end
end

app/views/countries/index.html.slim
/ SEO /////////////////////////////////////////////////////////////////////////

- title       "Explore"
- description "Explore the countries available in the Tripmustsees database."
- keywords    "Tripmustsees countries"

///////////////////////////////////////////////////////////////////////////////
- content_for(:side_panel_right) do
  div.map
    div.map__canvas {
                      data-lat="0.0"
                      data-lng="0.0"
                      data-zoom="0"
                      data-markers-url="#{countries_path(format: :json)}"
                      data-marker-icon="#{image_path('pin_29x48.png')}"
                    }

h1 Explore

.row
  - @countries.each do |country|
    .col-sm-3
      = link_to country_slug_path(country_slug: country.slug), class: 'card card_country' do
        .card__image = image_tag country.primary_image.file.url(:medium)
        .card__title = country.name

  .col-sm-3
    = link_to new_country_path, class: 'card card_country' do
      .card__image = image_tag 'transparent_pixel.png'
      .card__text
        | Cannot find the country which you are looking for?
        br
        br
        | Add it!
      .card__title Add a country

app/views/countries/new.html.slim
.row
  .col-sm-6
    h1 Add a country
    p Contribute to tripmustsees.com by adding a missing country.

= form_for @country do |f|
  .row
    .col-sm-6
      .form-group
        = f.label :name
        = f.text_field :name, placeholder: 'What is the name of the country?', class: 'form-control'

  .row
    .col-sm-6
      .form-group
        = label_tag 'Location'
        p Drag, drop and zoom until you mark the country name on the map with the red circle.
        .map.map_fixed-height
          .map__backsight
          .map__canvas {
                          data-lat="#{@country.latitude}"
                          data-lng="#{@country.longitude}"
                          data-zoom="#{@country.default_zoom_level}"
                          data-draggable="true"
                          data-zoomable="true"
                        }

          = f.text_field :latitude, class: 'map__input map__input_lat'
          = f.text_field :longitude, class: 'map__input map__input_lng'
          = f.text_field :default_zoom_level, class: 'map__input map__input_zoom-level'
  .row
    .col-sm-6
      .form-group
        = f.submit 'Add country', class: 'btn btn-primary'

app/views/countries/show.html.slim
/ SEO /////////////////////////////////////////////////////////////////////////

- title       "Explore #{@country.name}"
- description "Plan your trip and discover interesting places in #{@country.name}"
- keywords    @country.name

///////////////////////////////////////////////////////////////////////////////

- content_for(:side_panel_right) do
  div.map
    div.map__canvas {
                      data-lat="#{@country.latitude}"
                      data-lng="#{@country.longitude}"
                      data-zoom="#{@country.default_zoom_level}"
                      data-markers-url="#{country_cities_path(@country, format: :json)}"
                      data-marker-icon="#{image_path('pin_29x48.png')}"
                    }

h1 #{@country.name}

- if @country.general_information.present?
  p = @country.general_information.html_safe
  br

.row
  - @cities.each do |city|
    .col-sm-3
      = link_to city_slug_path(country_slug: @country.slug, city_slug: city.slug), class: 'card card_city' do
        .card__image = image_tag city.primary_image.file.url(:medium)
        .card__title = city.name
  .col-sm-3
    = link_to new_country_city_path(country_id: @country.id), class: 'card card_city' do
      .card__image = image_tag 'transparent_pixel.png'
      .card__text
        | Cannot find the city which you are looking for?
        br
        br
        | Add it!
      .card__title Add a city